# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/support/greeter/greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('spec/support/greeter/greeter.proto', syntax: :proto3) do
    add_message 'grpclog.Hello' do
      optional :name, :string, 1
      optional :error_code, :int64, 2
    end
  end
end

module Grpclog
  Hello = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('grpclog.Hello').msgclass
end
